# Generated by Django 4.1.3 on 2022-11-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('can_borrow_book_num', models.IntegerField(verbose_name='可借书数量')),
                ('can_borrow_days', models.IntegerField(verbose_name='可借书天数')),
                ('can_renew_times', models.IntegerField(verbose_name='可续借次数')),
                ('punish_rate', models.DecimalField(decimal_places=2, help_text='超过可借书天数后，每本每天多少钱', max_digits=2, verbose_name='罚款率（元/天）')),
                ('valid_year', models.IntegerField(help_text='0 为永久有效', verbose_name='有效期（年）')),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='sex',
            field=models.CharField(choices=[(1, '男'), (2, '女')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.readertype'),
        ),
    ]
