# Generated by Django 4.1.3 on 2022-11-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_readertype_reader_phone_number_reader_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readertype',
            name='punish_rate',
            field=models.DecimalField(decimal_places=2, help_text='超过可借书天数后，每本每天多少钱', max_digits=4, verbose_name='罚款率（元/天）'),
        ),
    ]
