# Generated by Django 4.1.3 on 2022-11-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.BigIntegerField(verbose_name='读者ID')),
                ('book_id', models.BigIntegerField(verbose_name='图书ID')),
                ('renew_times', models.IntegerField(verbose_name='续借次数')),
                ('created_times', models.DateTimeField(verbose_name='创建时间/借书时间')),
                ('plan_return_time', models.DateTimeField(verbose_name='应还时间')),
                ('return_time', models.DateTimeField(verbose_name='实际还书时间')),
                ('overdue_days', models.IntegerField(verbose_name='超期天数')),
                ('overdue_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='超期金额（应罚款金额）')),
                ('publish_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='罚款金额')),
                ('returned', models.CharField(choices=[(1, '是'), (2, '否')], max_length=1, null=True, verbose_name='是否已还书')),
            ],
        ),
    ]
